version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.instance.hostname=eureka-server
    ports:
      - "8761:8761"

  postgres:
    image: postgres:13
    container_name: postgres2
    environment:
      - POSTGRES_DB=laboratoire
      - POSTGRES_USER=idhem
      - POSTGRES_PASSWORD=idhem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data2

  laboratoire:
    build:
      context: ./laboratoire
    container_name: laboratoire
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres2:5432/laboratoire
      - SPRING_DATASOURCE_USERNAME=idhem
      - SPRING_DATASOURCE_PASSWORD=idhem
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - postgres

volumes:
  postgres_data2: