spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laboratory
    username: idhem
    password: idhem
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8050