server:
  port: 8081

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


keycloak:
  client-id: auth-service-v1
  client-secret: bzFGvg9Fxw20tDe80rm1aQkkozLkA2UB
  get-token-url: http://localhost:9090/realms/master/protocol/openid-connect/token
  issuer-url: http://localhost:9090/realms/master
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: redis