version: "3.8"  # or "3.9" or omit version for Docker Compose v2+

services:
  keycloak1:
    image: quay.io/keycloak/keycloak:20.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres1  # Change from 'postgres' to 'postgres1'
      KC_DB_URL_DATABASE: keycloak_v1
      KC_DB_PASSWORD: root
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin                # Add this line for the admin username
      KEYCLOAK_ADMIN_PASSWORD: admin       # Add this line for the admin password
      KEYCLOAK_JDBC_PARAMS: 'sslmode=require'
    ports:
      - "9090:8080"
    depends_on:
      postgres1:
        condition: service_healthy
    networks:
      network_sso:

  postgres1:
    image: postgres:13
    command: [ "postgres", "-c", "max_connections=200", "-c", "shared_buffers=24MB", "-c", "listen_addresses=*" ]
    environment:
      POSTGRES_DB: keycloak_v1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
    ports:
      - "5436:5432"
    networks:
      network_sso:
    volumes:
      - postgres_data:/var/lib/postgresql/data2
    user: postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "root"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  network_sso:
