spring:
  application:
    name: laboratoire
  datasource:
    username: idhem
    url: jdbc:postgresql://localhost:5432/laboratoire
    password: idhem
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

