spring:
  application:
    name: laboratoire
  zipkin:
    base-url: http://localhost:9411

  datasource:
    username: 'idhem'
    url: jdbc:postgresql://localhost:5432/laboratoires
    password: 'idhem'
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

