spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: laboratoire
          uri: lb://LABORATOIRE
          predicates:
            - Path=/api/v1/laboratoires/**
        - id: contact
          uri: lb://LABORATOIRE
          predicates:
            - Path=/api/v1/contacts-laboratoire/**
        - id: address
          uri: lb://LABORATOIRE
          predicates:
            - Path=/api/v1/adresses/**
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
