spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: laboratoire
          uri: lb://LABORATOIRE
          predicates:
            - Path=/api/v1/laboratoires/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
              - Path=/api/v1/auth/**
        - id: dossier-service
          uri: lb://DOSSIER-SERVICE
          predicates:
              - Path=Path=/api/v1/dossiers
              - Path=Path=/api/v1/analyses
              - Path=Path=/api/v1/epreuves
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
