# .github/workflows/laboratoire-backend.yml
name: Laboratoire Backend Pipeline

on:
  push:
    branches:
      - devops
    paths:
      - backend/laboratoire/**
      - .github/workflows/*-backend-laboratoire.yml
  pull_request:
    branches:
      - devops
    paths:
      - backend/laboratoire/**
      - .github/workflows/*-backend-laboratoire.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile Laboratoire
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Compile Laboratoire
        run: |
          cd backend/laboratoire
          mvn clean compile

  unit-test:
    runs-on: ubuntu-latest
    name: Unit Test Laboratoire
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: laboratoire
          POSTGRES_USER: idhem
          POSTGRES_PASSWORD: idhem
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: laboratoire
          DB_USER: idhem
          DB_PASSWORD: idhem
        run: |
          cd backend/laboratoire
          mvn clean test

  build:
    runs-on: ubuntu-latest
    name: Build Laboratoire
    needs: [compile, unit-test]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: laboratoire
          POSTGRES_USER: idhem
          POSTGRES_PASSWORD: idhem
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Build Laboratoire
        run: |
          cd backend/laboratoire
          mvn clean package

  build-image:
    runs-on: ubuntu-latest
    name: Build and Push Laboratoire Docker Image
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Extract Project Version
        id: extract_version
        run: |
          cd backend/laboratoire
          echo "VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Laboratoire Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: backend/laboratoire
          file: backend/laboratoire/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laboratoire:${{ steps.extract_version.outputs.VERSION }}
          build-args: |
            PROFILE=docker
            VERSION=${{ steps.extract_version.outputs.VERSION }}
