# .github/workflows/eureka-backend.yml
name: Eureka Backend Pipeline

on:
  push:
    branches:
      - devops
    paths:
      - backend/eureka-server/**
      - .github/workflows/*-backend-eureka.yml
  pull_request:
    branches:
      - devops
    paths:
      - backend/eureka-server/**
      - .github/workflows/*-backend-eureka.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile Eureka Server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Compile Eureka Server
        run: |
          cd backend/eureka-server
          mvn clean compile

  unit-test:
    runs-on: ubuntu-latest
    name: Unit Test Eureka Server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Run Tests
        run: |
          cd backend/eureka-server
          mvn clean test

  build:
    runs-on: ubuntu-latest
    name: Build Eureka Server
    needs: [compile, unit-test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Build Eureka Server
        run: |
          cd backend/eureka-server
          mvn clean package

  build-image:
    runs-on: ubuntu-latest
    name: Build and Push Eureka Docker Image
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
      - name: Extract Project Version
        id: extract_version
        run: |
          cd backend/eureka-server
          echo "VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Eureka Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: backend/eureka-server
          file: backend/eureka-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:${{ steps.extract_version.outputs.VERSION }}
