name: Laboratoire frontend Pipeline

on:
  push:
    branches:
      - devops
    paths:
      - frontend/**
      - .github/workflows/pipeline-client-angular.yml
  pull_request:
    branches:
      - devops
    paths:
      - frontend/**
      - .github/workflows/pipeline-client-angular.yml

jobs:
  test:
    name: Testing angular app using Jest
    runs-on: ubuntu-latest
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # {4}
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      # {5}
      - name: Run tests
        run: npm test
  build:
    name: building application
    runs-on: ubuntu-latest
    needs: test
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v3

      # {3}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # {4}
      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build
        run: npm run build
